Repository rivosinc/hubris, pull requests merged in 2022-09, with the labels that each got.

#2 Format
  build/util/src/lib.rs
  build/xtask/src/dist.rs
  sys/kern/build.rs
  sys/kern/src/arch/riscv32.rs
  sys/userlib/src/arch/arm_m.rs
Labels: bug, enhancement

#3 Tests to validate memory protection
  test/test-api/src/lib.rs
  test/test-assist/src/main.rs
  test/test-suite/src/main.rs
Labels: enhancement

#4 Update CI
  .github/workflows/dist.yml
Labels: enhancement

#5 chips: Add `qemu.sh` to the chip files.
  build/xtask/src/dist.rs
  chips/fe310-g002/qemu.sh
  chips/fe310-g003/qemu.sh
Labels: enhancement

#8 riscv task linker scripts: Add .sdata input section to .data output section
  build/riscv-task-link.x
  build/riscv-task-rlink.x
  build/riscv-task-tlink.x
Labels: bug

#32 Orphaned linker sections now cause errors
  build/xtask/src/dist.rs
  lds/rv32/kernel-link.x
  lds/rv32/task-link.x
  lds/rv32/task-rlink.x
  lds/rv32/task-tlink.x
Labels: enhancement
